### ISSUE TITLE
Fn-toggle stops working after some time

### ISSUE THREAD

**Issue by dieterdemeyer** [bikkelbroeders/TouchBarDemoApp#5] opened 2016-11-06 14:43 UTC
Hello,

I've been using the app for a few hours now during the weekend and I noticed that the Fn toggle stops working after a certain period of time.
When reenabling the "On-Screen Touch Bar" from the menu bar, it seems to be working again.

Anything I can do to help debug this ?

**Comment by AndreasVerhoeven** [comment] 2016-11-06 18:09
Hi Dieter,

Can you easily reproduce this behavior?

My best bet is that the "key presses" detection function is sometimes missing a "key up", event, which makes the app thinks another key is always pressed (in which case it won't pop up the Touch Bar - only single Fn presses will do).

**Comment by dieterdemeyer** [comment] 2016-11-06 18:47
Hello,

I have the TouchBarServer application running non stop.
Then after some time, pressing the Fn key doesn't show the TouchBar anymore.
The solution is to reenable it from the menubar, or as it turns out, wait some more and then it just works again for a period of time.  

Is there any logging behind the scenes that we can look at to find out where the problem is ?

**Comment by AndreasVerhoeven** [comment] 2016-11-06 18:50
There's no logging by default, but if you have Xcode it's fairly easy to add it yourself:
`TouchBarDelegate.m`, line 262: add `NSLog(@"Key event: %@ (%ld)", event, (unsigned long) pressedKeySet.count);`

**Comment by juststevede** [comment] 2016-11-06 19:28
Hi guys,

I have the same behavior. It is working great for some time but stops working and need to be disabled and enabled in the menubar to make it work again.

Steve

**Comment by AndreasVerhoeven** [comment] 2016-11-06 20:18
Not sure what's going on yet, but we're trying to track this. Difficulty is caused by the time it takes for it to stop working

**Comment by juststevede** [comment] 2016-11-06 20:22
I will try to narrow it down and provide more information.

Anyway thank you so much for sharing your awesome work!

**Comment by dieterdemeyer** [comment] 2016-11-06 21:18
Hi,

I can't seem to find the file `TouchBarDelegate.m`, only `AppDelegate.m`.
I assume that's the one you mean ?

This time, it stopped working coming out of sleep mode. After opening XCode, it worked again. But it seems very random, both in the moment it stops working as well in opening other applications where the functionality returns..

**Comment by AndreasVerhoeven** [comment] 2016-11-06 21:33
Sorry, my bad. It's this file: https://github.com/bikkelbroeders/TouchBarDemoApp/blob/master/TouchBarServer/AppDelegate.m

**Comment by robbertkl** [comment] 2016-11-07 16:04
@dieterdemeyer @juststevede We've just released [v1.2](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/tag/v1.2) which handles the Fn key in a completely different (and hopefully more reliable) way. Could you install this version and see if the issue is now gone?

**Comment by juststevede** [comment] 2016-11-07 16:07
I already downloaded the new version and will keep you posted. Again, thanks for sharing your work!

**Comment by dieterdemeyer** [comment] 2016-11-07 16:18
Same here. 
Installed new version and I will let you know..

**Comment by dieterdemeyer** [comment] 2016-11-07 20:29
I've been running the new version on 2 MacBooks for a few hours now without any issues.

**Comment by juststevede** [comment] 2016-11-07 22:22
I didn't have any issues anymore too. Well done!

**Comment by robbertkl** [comment] 2016-11-07 22:30
Awesome, I'll consider this resolved and close the issue. If ever it's coming back after all, just reopen or submit a new issue.

**Closed as completed by robbertkl** 2016-11-07 22:30 UTC
