### ISSUE TITLE
need a function that could put the bar to the bottle or side. 

### ISSUE THREAD

**Issue by NathanZhengNaixian** [bikkelbroeders/TouchBarDemoApp#23] opened 2016-11-08 09:29 UTC
we need a function that could put the bar to the bottle or side. 

Love the App. Bless you

**Comment by robbertkl** [comment] 2016-11-08 09:32
Closed as duplicate of #3. 

Please note we will never add the ability to put the Touch Bar on the side, since it's horizontal in orientation. But to the bottom, yes.

**Closed as completed by robbertkl** 2016-11-08 09:32 UTC
