### ISSUE TITLE
Allow scrolling by placing the cursor on status bar and scrolling without clicking

### ISSUE THREAD

**Issue by leo98gomez** [bikkelbroeders/TouchBarDemoApp#78] opened 2016-11-28 02:40 UTC
Currently we can scroll through the TouchBar by clicking and dragging along, but could it be possible to do it by placing the mouse cursor on top of it and just dragging along without having to click. I'm using an apple magic Mouse and since it can detect gestures it'll be kind of cool to be able to do it. It'll give it an actual feeling as if we were really dragging it along with out fingers in a way.

**Comment by robbertkl** [comment] 2016-11-28 06:21
Duplicate of #31

**Closed as completed by robbertkl** 2016-11-28 06:21 UTC
