### ISSUE TITLE
[Suggestion] Add a trackpad and wireless connectivity

### ISSUE THREAD

**Issue by jimcox7** [bikkelbroeders/TouchBarDemoApp#84] opened 2016-12-06 02:58 UTC
With the touch bar at the top of the iPad, then a keyboard and then a working trackpad underneath you'll have a killer app!

Loving the work! X

**Comment by robbertkl** [comment] 2016-12-06 13:36
Closed as duplicate of #26, #32, #60, #75 and #83.

**Closed as completed by robbertkl** 2016-12-06 13:36 UTC

**Comment by maxbaeumle** [comment] 2016-12-06 13:40
@robbertkl Perhaps you want to use Issue Templates to notify people of common "issues" before they are creating more duplicates: https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by robbertkl** [comment] 2016-12-06 13:41
Thx @maxbaeumle, I was actually JUST looking into that myself 😄. The duplicates are starting to get annoying, people don't even bother to search the issue list before submitting.
