### ISSUE TITLE
SUGGESTION: Trackpad Support

### ISSUE THREAD

**Issue by Happymanpm** [bikkelbroeders/TouchBarDemoApp#100] opened 2017-04-28 04:09 UTC
This app is amazing - I'm using it right now! 
The one thing that could make it better - a trackpad!
There's space right under the keyboard in every mode, and it would make this app incredible.

Thanks for reading

**Comment by robbertkl** [comment] 2017-05-02 13:21
Closed as duplicate of #26, #32, #60, #75, #83 and #84.

**Closed as completed by robbertkl** 2017-05-02 13:21 UTC
