### ISSUE TITLE
TrackPad Support Idea

### ISSUE THREAD

**Issue by par5ul1** [bikkelbroeders/TouchBarDemoApp#83] opened 2016-12-04 15:05 UTC
So I had just one more idea for adding trackpad support to the app. You could perhaps make the mac a vnc host and the ipad a client. Do you think that would be possible?

**Comment by bwesterhof** [comment] 2016-12-04 18:02
This would be awesome!

**Comment by robbertkl** [comment] 2016-12-04 19:09
No, this is a demo app for the Touch Bar, not a VNC client. There are hundreds of VNC apps in the App Store already.

Also, this is a duplicate of #26, #32, #60 and #75.

**Closed as completed by robbertkl** 2016-12-04 19:09 UTC
